### ISSUE TITLE
bvhio and Azure Kinect Data

### ISSUE THREAD

**Issue by Voelch** [Wasserwecken/bvhio#12]
Hello, 
I'm trying to create animations in Blender using Azure Kinect Body Tracking data. I'm attempting to transfer the coordinates of the body joints into a BVH file. I'm having trouble with the motion part. Your package seems quite good and well-documented, but some things are unclear to me. 

In your example, there's:
joint.Rotation *= bvhio.Euler.toQuatFrom((+0.523599,0,0))

Do I input the difference in Euler angles here? 

It probably is straightforward, given that I already have the motion data and even quaternions per frame by the Azure Kinect. Do you perhaps have a simple way to do this with your package?

**Comment by Wasserwecken** [comment]
In the line you quoted im adding a difference. Because of the the behaviour of quaterions.
Adding quaternions reqires multiplication. But you can also set the quaternion diretly if you want.

**Comment by Wasserwecken** [comment]
But im not sure if this is the corect package for your usecase. Blender already has a .bvh importer and exporter. And there are libraries that can stream kinect data to blender ;)

This package is intened to manipulate and read .bvh data.
