### ISSUE TITLE
README:  What does "- Y+ is up" mean

### ISSUE THREAD

**Issue by herdrick** [Wasserwecken/bvhio#4]
Can you change the following fragment of the README file: "Right-Handed, - Y+ is up, Z- is forward and positive rotations are counter clockwise."  The problem is the "- Y+ is up" part. Perhaps you want "Right-Handed, Y+ is up, Z- is forward...".

Also, "positive rotations are counter clockwise" is ambiguous, since it depends on whether you are viewing the rotation looking in the positive or negative direction of the axis.  You could say, "positive rotations are counter clockwise when viewed from the origin looking in the positive direction".

**Comment by Wasserwecken** [comment]
Readme has been updated. Thanks for the hints!
