### ISSUE TITLE
Interpolating between frames

### ISSUE THREAD

**Issue by dj-kefir-siorbacz** [Wasserwecken/bvhio#7]
Hi @Wasserwecken ! 
(No hurry, btw., don't feel pressured to answer)

I have an animation file and I want to cut a range of frames for it.

Let's say this animation file has 100 frames and I want to only leave the part from frame 25 to frame 75 (both-inclusive)

```python
cuts = {
"<path-to-bvh>" : [24,74]
}

for k,v in cuts.items():
    for start, end in v:
        bvh = bvhio.readAsBvh(k)
        root = bvhio.convertBvhToHierarchy(bvh.Root)

        # write ground truth
        path = Path(output_path) / f"{Path(k).name}_{start}_{end}_GROUND_TRUTH.bvh"
        for joint, _, _ in root.layout():
            joint.Keyframes = zip(range(0, end-start+1), [joint.Keyframes[i][1] for i in range(start, end+1)])
        bvhio.writeHierarchy(path, root, bvh.FrameTime, end - start + 1)

        # write linear interpolation
        path = Path(output_path) / f"{Path(k).name}_{start}_{end}_LIN_INTERP.bvh"
        for joint, _, _ in root.layout():
            joint.Keyframes = [(0, root.Keyframes[0][1]), (end-start, root.Keyframes[-1][1]) ]
        bvhio.writeHierarchy(path, root,  bvh.FrameTime,  end - start + 1)

```
        
The so called "ground-truth" is written correctly, however the linear interpolation doesn't work - it produces a completely messed up animation. Am I doing the interpolation wrong?

**Comment by Wasserwecken** [comment]
Do you have a sample file for me to try it out?

**Comment by dj-kefir-siorbacz** [comment]
Here you are: 
https://drive.google.com/file/d/1lNXQ6KsBSrFvr62sqFN2yn5oFAbC3lsm/view?usp=sharing

Let's say the `cuts` is: 
```
cuts = {
"<path-to-bvh>" : [0,38]
}
```

**Comment by dj-kefir-siorbacz** [comment]
You should see that "ground-truth" is correctly cut, while linear interpolation is completely broken - it has position channels for every joint, but of the kind that you can't easily delete using the method from https://github.com/Wasserwecken/bvhio/issues/5

**Comment by Wasserwecken** [comment]
I have good and bad news here. The good one is, your code has a simple bug that will fix the broken animation:

This will copy the animation data of the root to all other joints.
`joint.Keyframes = [(0, root.Keyframes[0][1]), (end-start, root.Keyframes[-1][1]) ]`

But you should return the animation data of the joint itself like this:
`joint.Keyframes = [(0, joint.Keyframes[0][1]), (end-start, joint.Keyframes[-1][1]) ]`

But the bad new is that the interpolation looks horrible. the code uses the GLM lerp-method for interpolation and the local offset data is interpolated:
```
Transform(
    name=f'Key {frame} (interpolated)',
    position=glm.lerp(before[1].Position, after[1].Position, weight),
    rotation=glm.lerp(before[1].Rotation, after[1].Rotation, weight),
    scale=glm.lerp(before[1].Scale, after[1].Scale, weight)
), keep=None
```

To impove the interpolation feature, I gues the world data of restpose + animation has to be interpolated. Unfortunatly this is not implemented. But feel free to create a pull request :)

**Comment by dj-kefir-siorbacz** [comment]
Oh, yeah, you're right! 

Shouldn't rotations be interpolated using `slerp`? 

Either way, thanks!
